// import Icons
import "bootstrap-icons/font/bootstrap-icons.css";

// import bootstrap
import "bootstrap/dist/css/bootstrap.css";

// import glightbox
import "glightbox/dist/css/glightbox.css";

import Script from "next/script";


import type { Metadata } from "next";
import { Playfair_Display } from "next/font/google";
import "./globals.css";

// Components
import Header from "./components/Header";
import BacktoTop from "./components/BackToTop";
import Footer from "./sections/Footer";

const playfair = Playfair_Display({ 
  subsets: ["latin"],
  display: "swap",
  variable: "--font-playfair-display",
  weight: ["400", "500", "600", "700", "800", "900"], 
});

export const metadata: Metadata = {
  title: "NextJS Restaurant Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={playfair.className}>
        <Header />
        {children}
        <Footer />
        <BacktoTop />
      </body>
      
      {/* Bootstrap 5.3.8 JS Bundle */}
      <Script
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-H4L7fSwwXU+78pDAn0G78R6cE4G8w/mby+9+7Z7e4N463m6D/M2G0fX4D4X5O8T9"
        crossOrigin="anonymous"
        strategy="afterInteractive"
      />
      
    </html>
  );
}
